name: Docker Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker-compose build
      
      - name: Start services
        run: |
          docker-compose up -d
          sleep 30
      
      - name: Check services health
        run: |
          docker-compose ps
          docker-compose logs
      
      - name: Test web application
        run: |
          curl -f http://localhost:3000 || exit 1
      
      - name: Stop services
        if: always()
        run: |
          docker-compose down -v

